version: "3.8"

services:
  laravel.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
    image: sail-8.3/app
    container_name: qlanka-app
    working_dir: /var/www/html
    environment:
      LARAVEL_SAIL: 1
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    command: /usr/bin/env sh -lc 'php -v && php artisan serve --host=0.0.0.0 --port=8000'
    networks:
      - sail

networks:
  sail:
    driver: bridge
